version: "3.8"

services:
  db:
    image: postgres:11.8
    restart: always
    container_name: tasks-demo-postgres
    volumes:
      - data-volume:/var/lib/db
    env_file:
      - database.env
    ports:
      - 5432:5432

volumes:
  data-volume: